name: Update badges

on:
  workflow_dispatch: # run manually
  schedule:
    # Runs at 1am UTC on Sunday
    - cron: "0 1 * * 0"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: michael-m-botelho # optional, but default will use the same from github
          #BADGE_SIZE: the resolution to the badges images # optional, 110x110 default

